
import java.awt.Desktop;
import java.awt.Toolkit;
import java.io.File;
import java.net.HttpURLConnection;
import java.net.URL;
import java.util.Arrays;
import java.util.Properties;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.activation.DataHandler;
import javax.activation.DataSource;
import javax.activation.FileDataSource;
import javax.mail.BodyPart;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Multipart;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.HyperlinkEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author SAURABH SINGH RAJPUT
 */
public final class JavaMail extends javax.swing.JFrame {
String rep,from,to,msg,sub,rep1,from1,to1,msg1,sub1,rep2,from2,to2,msg2,sub2;
 char[] pass=new char[20];
 char[] pass3=new char[20];
 char[] pass5=new char[20];
 Session session;
  Session session1;
  String fname="";
   Session session2;
   private Pattern pattern;
	private Matcher matcher;

	private static final String EMAIL_PATTERN = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
			+ "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$";
    /**
     * Creates new form JavaMail
     */
    public JavaMail() {
        initComponents();
        pattern = Pattern.compile(EMAIL_PATTERN);
        jpn4.setVisible(false);
        jpn7.setVisible(false);
        jpn5.setVisible(false);
        jl8.setVisible(false);
        jl9.setVisible(false);
        jep5.setEditable(false);
        jep1.setEditable(false);
        jep4.setEditable(false);
        jl10.setVisible(false);
        netcheck();
        setIcon();
    }
     public void netcheck()
    {
       
			try {
				URL url = new URL("http://www.google.com");
				
				HttpURLConnection con = (HttpURLConnection) url
						.openConnection();
				con.connect();
				if (con.getResponseCode() == 200){
					
				}
			} catch (Exception exception) {
				JOptionPane.showMessageDialog(this,"Internet is required to run this application.");
                                jb1.setEnabled(false);
                                jb2.setEnabled(false);
                                jb3.setEnabled(false);
			}
		
    }
     public  boolean validate(final String email) {

		matcher = pattern.matcher(email);
		return matcher.matches();

	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jt3 = new javax.swing.JTextField();
        jp1 = new javax.swing.JPasswordField();
        jt1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtf1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jl8 = new javax.swing.JLabel();
        jb1 = new javax.swing.JButton();
        jpn4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jep1 = new javax.swing.JEditorPane();
        jt2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jlb1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jt4 = new javax.swing.JTextField();
        jp2 = new javax.swing.JPasswordField();
        jt5 = new javax.swing.JTextField();
        jt6 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtf2 = new javax.swing.JTextArea();
        jl9 = new javax.swing.JLabel();
        jb2 = new javax.swing.JButton();
        jpn7 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jep5 = new javax.swing.JEditorPane();
        jButton2 = new javax.swing.JButton();
        jlb2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jt7 = new javax.swing.JTextField();
        jp3 = new javax.swing.JPasswordField();
        jt8 = new javax.swing.JTextField();
        jt9 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtf3 = new javax.swing.JTextArea();
        jb3 = new javax.swing.JButton();
        jl10 = new javax.swing.JLabel();
        jpn5 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jep4 = new javax.swing.JEditorPane();
        jButton3 = new javax.swing.JButton();
        jlb3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Java Mailer");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setForeground(new java.awt.Color(102, 0, 0));
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N

        jPanel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPanel1FocusLost(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
        });

        jt3.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jt3.setForeground(new java.awt.Color(51, 51, 51));
        jt3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jt3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jt3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jt3FocusLost(evt);
            }
        });
        jt3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jt3MouseReleased(evt);
            }
        });

        jp1.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jp1.setForeground(new java.awt.Color(51, 51, 51));
        jp1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jp1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jt1.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jt1.setForeground(new java.awt.Color(51, 51, 51));
        jt1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jt1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jtf1.setColumns(20);
        jtf1.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jtf1.setForeground(new java.awt.Color(51, 51, 51));
        jtf1.setRows(5);
        jtf1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(jtf1);

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("From:");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Password:");

        jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("To:");

        jLabel6.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Subject:");

        jLabel7.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Message:");

        jl8.setIcon(new javax.swing.ImageIcon("C:\\Users\\SAURABH SINGH RAJPUT\\Documents\\NetBeansProjects\\loading-bar.gif")); // NOI18N

        jb1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jb1.setText("Send");
        jb1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb1ActionPerformed(evt);
            }
        });

        jep1.setEditable(false);
        jep1.setBackground(new java.awt.Color(204, 204, 255));
        jep1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jep1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jep1.setForeground(new java.awt.Color(255, 0, 0));
        jScrollPane2.setViewportView(jep1);

        javax.swing.GroupLayout jpn4Layout = new javax.swing.GroupLayout(jpn4);
        jpn4.setLayout(jpn4Layout);
        jpn4Layout.setHorizontalGroup(
            jpn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jpn4Layout.setVerticalGroup(
            jpn4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
        );

        jt2.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jt2.setForeground(new java.awt.Color(51, 51, 51));
        jt2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jt2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Attach");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jlb1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jlb1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(84, 84, 84)
                            .addComponent(jb1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(jLabel7))
                            .addGap(7, 7, 7)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                                .addComponent(jt1)
                                .addComponent(jp1)
                                .addComponent(jt3)
                                .addComponent(jt2)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jl8)
                .addGap(120, 120, 120))
            .addComponent(jpn4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(139, 139, 139)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jt2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jt3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jp1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jt1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlb1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jl8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jpn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Gmail", jPanel1);

        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("From:");

        jLabel9.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Password:");

        jLabel10.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("To:");

        jLabel11.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Subject:");

        jLabel12.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Message:");

        jt4.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jt4.setForeground(new java.awt.Color(51, 51, 51));
        jt4.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jt4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jt4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jt4FocusLost(evt);
            }
        });
        jt4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jt4MouseReleased(evt);
            }
        });

        jp2.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jp2.setForeground(new java.awt.Color(51, 51, 51));
        jp2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jp2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jt5.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jt5.setForeground(new java.awt.Color(51, 51, 51));
        jt5.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jt5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jt6.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jt6.setForeground(new java.awt.Color(51, 51, 51));
        jt6.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jt6.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jtf2.setColumns(20);
        jtf2.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jtf2.setForeground(new java.awt.Color(51, 51, 51));
        jtf2.setRows(5);
        jtf2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane3.setViewportView(jtf2);

        jl9.setIcon(new javax.swing.ImageIcon("C:\\Users\\SAURABH SINGH RAJPUT\\Documents\\NetBeansProjects\\loading-bar.gif")); // NOI18N

        jb2.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jb2.setText("Send");
        jb2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb2ActionPerformed(evt);
            }
        });

        jep5.setBorder(null);
        jep5.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jep5.setForeground(new java.awt.Color(255, 0, 0));
        jScrollPane8.setViewportView(jep5);

        javax.swing.GroupLayout jpn7Layout = new javax.swing.GroupLayout(jpn7);
        jpn7.setLayout(jpn7Layout);
        jpn7Layout.setHorizontalGroup(
            jpn7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
        );
        jpn7Layout.setVerticalGroup(
            jpn7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setText("Attach");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jlb2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpn7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(jLabel12))
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                            .addComponent(jt6)
                            .addComponent(jt5)
                            .addComponent(jp2)
                            .addComponent(jt4)
                            .addComponent(jlb2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jl9)
                        .addGap(122, 122, 122))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb2, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jt4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jp2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jt5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(139, 139, 139)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jt6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jlb2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jl9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jpn7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Rediffmail", jPanel2);

        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("From:");

        jLabel14.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Password:");

        jLabel15.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("To:");

        jLabel16.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel16.setText("Subject:");

        jLabel17.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Message:");

        jt7.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jt7.setForeground(new java.awt.Color(51, 51, 51));
        jt7.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jt7.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jt7.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jt7FocusLost(evt);
            }
        });
        jt7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jt7MouseReleased(evt);
            }
        });

        jp3.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jp3.setForeground(new java.awt.Color(51, 51, 51));
        jp3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jp3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jt8.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jt8.setForeground(new java.awt.Color(51, 51, 51));
        jt8.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jt8.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jt9.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jt9.setForeground(new java.awt.Color(51, 51, 51));
        jt9.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jt9.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jtf3.setColumns(20);
        jtf3.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jtf3.setForeground(new java.awt.Color(51, 51, 51));
        jtf3.setRows(5);
        jtf3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane4.setViewportView(jtf3);

        jb3.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        jb3.setText("Send");
        jb3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb3ActionPerformed(evt);
            }
        });

        jl10.setIcon(new javax.swing.ImageIcon("C:\\Users\\SAURABH SINGH RAJPUT\\Documents\\NetBeansProjects\\loading-bar.gif")); // NOI18N

        jep4.setBorder(null);
        jep4.setFont(new java.awt.Font("Segoe UI Semilight", 1, 14)); // NOI18N
        jep4.setForeground(new java.awt.Color(255, 0, 0));
        jScrollPane7.setViewportView(jep4);

        javax.swing.GroupLayout jpn5Layout = new javax.swing.GroupLayout(jpn5);
        jpn5.setLayout(jpn5Layout);
        jpn5Layout.setHorizontalGroup(
            jpn5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
        );
        jpn5Layout.setVerticalGroup(
            jpn5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
        );

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton3.setText("Attach");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jlb3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jl10)
                        .addGap(120, 120, 120))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(jLabel17))
                            .addComponent(jButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                            .addComponent(jt9)
                            .addComponent(jt8)
                            .addComponent(jp3)
                            .addComponent(jt7)
                            .addComponent(jlb3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb3, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jt7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jp3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jt8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(139, 139, 139)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jt9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jl10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jpn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Yahoo", jPanel3);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Java Mailer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jt3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jt3FocusLost

    }//GEN-LAST:event_jt3FocusLost

    private void jt3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt3MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jt3MouseReleased

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("e_mail.png")));
    }
class msgsend extends Thread
{
    @Override
    public void run()
    {
       
  
  //Get the session object  
  Properties props = new Properties();  
  props.put("mail.smtp.host", "smtp.gmail.com");  
  props.put("mail.smtp.socketFactory.port", "465");  
  props.put("mail.smtp.socketFactory.class",  
            "javax.net.ssl.SSLSocketFactory");  
  props.put("mail.smtp.auth", "true");  
  props.put("mail.smtp.port", "465");  
 
  session = Session.getDefaultInstance(props,  
   new javax.mail.Authenticator() {  
   protected javax.mail.PasswordAuthentication getPasswordAuthentication() {  
   return new javax.mail.PasswordAuthentication(from,rep);//change accordingly  
   }  
  });
  
   
  //compose message  
   try{ 
   MimeMessage message = new MimeMessage(session);  
   message.setFrom(new InternetAddress(from));//change accordingly  
   message.addRecipient(Message.RecipientType.TO,new InternetAddress(to));  
   message.setSubject(sub);  
   
  if(fname.equals(""))
   {
       message.setText(msg+"\n\n\n-------\nSent from Java Mailer\nDeveloped by: Saurabh Singh Rajput\nMob:9851066082\nvisit:www.saurabhsinghrajput.com ");  
   
   } 
  else 
  {
   BodyPart messageBodyPart = new MimeBodyPart();
   messageBodyPart.setText(msg+"\n\n\n-------\nSent from Java Mailer\nDeveloped by: Saurabh Singh Rajput\nMob:9851066082\nvisit:www.saurabhsinghrajput.com ");  
   MimeBodyPart messageBodyPart2 = new MimeBodyPart();
   String filename = fname;
   DataSource source = new FileDataSource(filename);
   messageBodyPart2.setDataHandler(new DataHandler(source));
   messageBodyPart2.setFileName(filename);
   Multipart multipart = new MimeMultipart();  
   multipart.addBodyPart(messageBodyPart);
   multipart.addBodyPart(messageBodyPart2);  
   message.setContent(multipart); 
      }
   
   //send message  
   Transport.send(message); 
   jl8.setVisible(false);
   jb1.setEnabled(true);
   JOptionPane.showMessageDialog(rootPane,"Successfully send.");
  
        
        jt1.setText("");
        jt2.setText("");
       jtf1.setText("");
       jlb1.setText("");
       fname="";
  } catch (MessagingException e) 
   { 
    jl8.setVisible(false);
    jpn4.setVisible(true);
    jb1.setEnabled(true);
    jep1.setContentType("text/html");
    jep1.setEditable(false);
    jep1.addHyperlinkListener((HyperlinkEvent hle) -> {
        if (HyperlinkEvent.EventType.ACTIVATED.equals(hle.getEventType())) {
            
            Desktop desktop = Desktop.getDesktop();
            try {
                desktop.browse(hle.getURL().toURI());
            } catch (Exception ex) {
                System.out.println("");
            }
        }
    });
    
    jep1.setText("Email or password is worng or do less secure app is on at <a href=\"https://myaccount.google.com/security\">Here</a>");
      //JOptionPane.showMessageDialog(rootPane,"Something error..please try again.or do less secure app is on in your account");
    } 
   
 }
}
class msgsend1 extends Thread
{
    @Override
    public void run()
    {
       
  
  //Get the session object  
Properties props = new Properties();  
props.put("mail.smtp.host", "smtp.rediffmail.com");  
props.put("mail.smtp.socketFactory.port", "465");  
props.put("mail.smtp.socketFactory.class","javax.net.ssl.SSLSocketFactory"); 
props.put("mail.smtp.port", "465"); 
props.put("mail.smtp.auth", "true");   
 
  session1 = Session.getDefaultInstance(props,  
   new javax.mail.Authenticator() {  
   protected javax.mail.PasswordAuthentication getPasswordAuthentication() {  
   return new javax.mail.PasswordAuthentication(from1,rep1);//change accordingly  
   }  
  });
  
   
  //compose message  
   try{ 
   MimeMessage message = new MimeMessage(session1);  
   message.setFrom(new InternetAddress(from1));//change accordingly  
   message.addRecipient(Message.RecipientType.TO,new InternetAddress(to1));  
   message.setSubject(sub1);  
   message.setText(msg1+"\n\n\n-------\nSent from Java Mailer\nDeveloped by: Saurabh Singh Rajput\nMob:9851066082\nvisit:www.saurabhsinghrajput.com ");  
     
   //send message  
   Transport.send(message); 
   jl9.setVisible(false);
   jb2.setEnabled(true);
   jpn7.setVisible(false);
   JOptionPane.showMessageDialog(rootPane,"Successfully send.");
    jt5.setText("");
        jt6.setText("");
       jtf2.setText("");
  } 
   catch (MessagingException e) 
   { 
    jl9.setVisible(false);
    jpn7.setVisible(true);
    jb2.setEnabled(true);
    jep5.setContentType("text/html");
    jep5.setEditable(false);
    
    jep5.setText("Email or password is worng.please try again.");
      //JOptionPane.showMessageDialog(rootPane,"Something error..please try again.or do less secure app is on in your account");
    } 
   
 }
}
class msgsend2 extends Thread
{
    @Override
    public void run()
    {
       
  
  //Get the session object  
  Properties props = new Properties();  
  props.put("mail.smtp.host", "smtp.mail.yahoo.com");  
  props.put("mail.smtp.socketFactory.port", "465");  
  props.put("mail.smtp.socketFactory.class",  
            "javax.net.ssl.SSLSocketFactory");  
  props.put("mail.smtp.auth", "true");  
  props.put("mail.smtp.port", "465");  
 
  session2 = Session.getDefaultInstance(props,  
   new javax.mail.Authenticator() {  
   protected javax.mail.PasswordAuthentication getPasswordAuthentication() {  
   return new javax.mail.PasswordAuthentication(from2,rep2);//change accordingly  
   }  
  });
  
   
  //compose message  
   try{ 
   MimeMessage message = new MimeMessage(session2);  
   message.setFrom(new InternetAddress(from2));//change accordingly  
   message.addRecipient(Message.RecipientType.TO,new InternetAddress(to2));  
   message.setSubject(sub2);  
   message.setText(msg2+"\n\n\n-------\nSent from Java Mailer\nDeveloped by: Saurabh Singh Rajput\nMob:9851066082\nvisit:www.saurabhsinghrajput.com");  
     
   //send message  
   Transport.send(message); 
   jl10.setVisible(false);
   jb3.setEnabled(true);
   JOptionPane.showMessageDialog(rootPane,"Successfully send.");
    jt8.setText("");
    jt9.setText("");
    jtf3.setText("");
  } catch (MessagingException e) 
   { 
    jl10.setVisible(false);
    jpn5.setVisible(true);
    jb3.setEnabled(true);
    jep4.setContentType("text/html");
    jep4.setEditable(false);
    
    jep4.setText("Either Email or password is worng.please check and try again.");
      //JOptionPane.showMessageDialog(rootPane,"Something error..please try again.or do less secure app is on in your account");
    } 
   
 }
}

class netcheckpannelentered extends Thread
{
    public void run()
    {
        try {
				URL url = new URL("http://www.google.com");
				
				HttpURLConnection con = (HttpURLConnection) url
						.openConnection();
				con.connect();
				if (con.getResponseCode() == 200){
				jb1.setEnabled(true);
                                jb2.setEnabled(true);
                                jb3.setEnabled(true);
                                jpn4.setVisible(false);
                                jpn7.setVisible(false);
                                jpn5.setVisible(false);
                                jep1.setText("");
                                jep4.setText("");
                                jep5.setText("");
				}
			} catch (Exception exception) {
				//JOptionPane.showMessageDialog(rootPane,"Internet is required to run this application.");
                                
                                jb1.setEnabled(false);
                                jb2.setEnabled(false);
                                jb3.setEnabled(false);
                                jpn4.setVisible(true);
                                jpn7.setVisible(true);
                                jpn5.setVisible(true);
                                 jep1.setText("Internet connection is required.");
                                 jep4.setText("Internet connection is required.");
                                 jep5.setText("Internet connection is required.");
			} // TODO add your handling code here:
    
    }
}
    private void jb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb1ActionPerformed
        from=jt3.getText();
         pass = jp1.getPassword();
        String pass1= Arrays.toString(pass);
        rep = pass1.replace(',',' ').replace('[',' ').replace(']',' ').trim().replaceAll(" ","");
        to=jt1.getText();
        sub=jt2.getText();
        msg=jtf1.getText();
        if(from.equals("")|rep.equals("")|to.equals("")|sub.equals(""))
        {  
            JOptionPane.showMessageDialog(this,"Please fill all details");
        } else {
              if(validate(from))
              {
                  if(validate(to))
                  {
                        msgsend msg=new msgsend();
                        msg.start();
                        jb1.setEnabled(false);
                        jl8.setVisible(true);
                        jpn4.setVisible(false);
                  }
                  else
                  {
                      JOptionPane.showMessageDialog(this,"Please enter receiver's email, correctly.");
                  }
            
              }
              else
              {
                JOptionPane.showMessageDialog(this,"Please enter sender's email, correctly.");  
              }

        }

    }//GEN-LAST:event_jb1ActionPerformed

    private void jt4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jt4FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jt4FocusLost

    private void jt4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt4MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jt4MouseReleased

    private void jt7FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jt7FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jt7FocusLost

    private void jt7MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt7MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jt7MouseReleased

    private void jb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb2ActionPerformed
        from1=jt4.getText();
         pass3 = jp2.getPassword();
       String pass4= Arrays.toString(pass3);
        rep1 = pass4.replace(',',' ').replace('[',' ').replace(']',' ').trim().replaceAll(" ","");
        to1=jt5.getText();
        sub1=jt6.getText();
        msg1=jtf2.getText();
        if(from1.equals("")|rep1.equals("")|to1.equals("")|sub1.equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please fill all details");
        } else {
               if(validate(from1))
              {
                  if(validate(to1))
                  {
                        msgsend1 msg1=new msgsend1();
                        msg1.start();
                        jb2.setEnabled(false);
                        jl9.setVisible(true);
                        jpn7.setVisible(false);
                  }
                  else
                  {
                      JOptionPane.showMessageDialog(this,"Please enter receiver's email, correctly.");
                  }
            
              }
              else
              {
                JOptionPane.showMessageDialog(this,"Please enter sender's email, correctly.");  
              }
          /*  msgsend1 msg1=new msgsend1();
            msg1.start();
            jb2.setEnabled(false);
            jl9.setVisible(true);
            jpn7.setVisible(false);
           */
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jb2ActionPerformed

    private void jPanel1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1FocusLost

    private void jPanel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel1FocusGained
      
    }//GEN-LAST:event_jPanel1FocusGained

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
      netcheckpannelentered p1=new netcheckpannelentered();
      p1.start();  // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1MouseEntered

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
netcheckpannelentered p2=new netcheckpannelentered();
      p2.start();        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel2MouseEntered

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
netcheckpannelentered p3=new netcheckpannelentered();
      p3.start();        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

JFileChooser c=new JFileChooser();
c.showOpenDialog(null);
File f=c.getSelectedFile();


fname=f.getAbsolutePath();

if(fname.equals(""))
{
  jlb1.setText("");  
}
else
{
  jlb1.setText(fname);  
}
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb3ActionPerformed
        from2=jt7.getText();
        pass5 = jp3.getPassword();
        String pass6= Arrays.toString(pass5);
        rep2 = pass6.replace(',',' ').replace('[',' ').replace(']',' ').trim().replaceAll(" ","");
        to2=jt8.getText();
        sub2=jt9.getText();
        msg2=jtf3.getText();
        if(from2.equals("")|rep2.equals("")|to2.equals("")|sub2.equals(""))
        {
            JOptionPane.showMessageDialog(this,"Please fill all details");
        } else {
            if(validate(from2))
            {
                if(validate(to2))
                {
                    msgsend2 msg2=new msgsend2();
                    msg2.start();
                    jb3.setEnabled(false);
                    jl10.setVisible(true);
                    jpn5.setVisible(false);
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Please enter receiver's email, correctly.");
                }

            }
            else
            {
                JOptionPane.showMessageDialog(this,"Please enter sender's email, correctly.");
            }
            /*  msgsend2 msg2=new msgsend2();
            msg2.start();
            jb3.setEnabled(false);
            jl10.setVisible(true);
            jpn5.setVisible(false);
            */
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jb3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JavaMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JavaMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JavaMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JavaMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JavaMail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jb1;
    private javax.swing.JButton jb2;
    private javax.swing.JButton jb3;
    private javax.swing.JEditorPane jep1;
    private javax.swing.JEditorPane jep4;
    private javax.swing.JEditorPane jep5;
    private javax.swing.JLabel jl10;
    private javax.swing.JLabel jl8;
    private javax.swing.JLabel jl9;
    private javax.swing.JLabel jlb1;
    private javax.swing.JLabel jlb2;
    private javax.swing.JLabel jlb3;
    private javax.swing.JPasswordField jp1;
    private javax.swing.JPasswordField jp2;
    private javax.swing.JPasswordField jp3;
    private javax.swing.JPanel jpn4;
    private javax.swing.JPanel jpn5;
    private javax.swing.JPanel jpn7;
    private javax.swing.JTextField jt1;
    private javax.swing.JTextField jt2;
    private javax.swing.JTextField jt3;
    private javax.swing.JTextField jt4;
    private javax.swing.JTextField jt5;
    private javax.swing.JTextField jt6;
    private javax.swing.JTextField jt7;
    private javax.swing.JTextField jt8;
    private javax.swing.JTextField jt9;
    private javax.swing.JTextArea jtf1;
    private javax.swing.JTextArea jtf2;
    private javax.swing.JTextArea jtf3;
    // End of variables declaration//GEN-END:variables
}
